Update Linting (#508)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [eslint](https://eslint.org) ([source](https://github.com/eslint/eslint)) | devDependencies | patch | [`9.39.3` -> `9.39.4`](https://renovatebot.com/diffs/npm/eslint/9.39.3/9.39.4) |
| [prettier](https://prettier.io) ([source](https://github.com/prettier/prettier)) | devDependencies | patch | [`3.8.1` -> `3.8.3`](https://renovatebot.com/diffs/npm/prettier/3.8.1/3.8.3) |
| [stylelint](https://stylelint.io) ([source](https://github.com/stylelint/stylelint)) | devDependencies | minor | [`17.4.0` -> `17.8.0`](https://renovatebot.com/diffs/npm/stylelint/17.4.0/17.8.0) |

---

### Release Notes

<details>
<summary>eslint/eslint (eslint)</summary>

### [`v9.39.4`](https://github.com/eslint/eslint/releases/tag/v9.39.4)

[Compare Source](https://github.com/eslint/eslint/compare/v9.39.3...v9.39.4)

#### Bug Fixes

- [`f18f6c8`](https://github.com/eslint/eslint/commit/f18f6c8ae92a1bcfc558f48c0bd863ea94067459) fix: update dependency minimatch to ^3.1.5 ([#&#8203;20564](https://github.com/eslint/eslint/issues/20564)) (Milos Djermanovic)
- [`a3c868f`](https://github.com/eslint/eslint/commit/a3c868f6ef103c1caff9d15f744f9ebd995e872f) fix: update dependency [@&#8203;eslint/eslintrc](https://github.com/eslint/eslintrc) to ^3.3.4 ([#&#8203;20554](https://github.com/eslint/eslint/issues/20554)) (Milos Djermanovic)
- [`234d005`](https://github.com/eslint/eslint/commit/234d005da6cd3c924f359e3783fbf565a3c047c3) fix: minimatch security vulnerability patch for v9.x ([#&#8203;20549](https://github.com/eslint/eslint/issues/20549)) (Andrej Beles)
- [`b1b37ee`](https://github.com/eslint/eslint/commit/b1b37eecaa033d2e390e1d8f1d6e68d0f5ff3a6a) fix: update `ajv` to `6.14.0` to address security vulnerabilities ([#&#8203;20538](https://github.com/eslint/eslint/issues/20538)) (루밀LuMir)

#### Documentation

- [`4675152`](https://github.com/eslint/eslint/commit/46751526037682f8b42abcfb3e06d19213719347) docs: add deprecation notice partial ([#&#8203;20520](https://github.com/eslint/eslint/issues/20520)) (Milos Djermanovic)

#### Chores

- [`b8b4eb1`](https://github.com/eslint/eslint/commit/b8b4eb15901c1bd6ef40d2589da4ae75795c0f6e) chore: update dependencies for ESLint v9.39.4 ([#&#8203;20596](https://github.com/eslint/eslint/issues/20596)) (Francesco Trotta)
- [`71b2f6b`](https://github.com/eslint/eslint/commit/71b2f6b628b76157b4a2a296cb969dc56abb296c) chore: package.json update for [@&#8203;eslint/js](https://github.com/eslint/js) release (Jenkins)
- [`1d16c2f`](https://github.com/eslint/eslint/commit/1d16c2fa3998440ae7b0f6e2612935bd6b0ded1d) ci: pin Node.js 25.6.1 ([#&#8203;20563](https://github.com/eslint/eslint/issues/20563)) (Milos Djermanovic)

</details>

<details>
<summary>prettier/prettier (prettier)</summary>

### [`v3.8.3`](https://github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#383)

[Compare Source](https://github.com/prettier/prettier/compare/3.8.2...3.8.3)

[diff](https://github.com/prettier/prettier/compare/3.8.2...3.8.3)

##### SCSS: Prevent trailing comma in `if()` function ([#&#8203;18471](https://github.com/prettier/prettier/pull/18471) by [@&#8203;kovsu](https://github.com/kovsu))

<!-- prettier-ignore -->

```scss
// Input
$value: if(sass(false): 1; else: -1);

// Prettier 3.8.2
$value: if(
  sass(false): 1; else: -1,
);

// Prettier 3.8.3
$value: if(sass(false): 1; else: -1);
```

### [`v3.8.2`](https://github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#382)

[Compare Source](https://github.com/prettier/prettier/compare/3.8.1...3.8.2)

[diff](https://github.com/prettier/prettier/compare/3.8.1...3.8.2)

##### Angular: Support Angular v21.2 ([#&#8203;18722](https://github.com/prettier/prettier/pull/18722), [#&#8203;19034](https://github.com/prettier/prettier/pull/19034) by [@&#8203;fisker](https://github.com/fisker))

Exhaustive typechecking with `@default never;`

<!-- prettier-ignore -->

```html
<!-- Input -->
@&#8203;switch (foo) {
  @&#8203;case (1) {}
  @&#8203;default never;
}

<!-- Prettier 3.8.1 -->
SyntaxError: Incomplete block "default never". If you meant to write the @&#8203; character, you should use the "&#&#8203;64;" HTML entity instead. (3:3)

<!-- Prettier 3.8.2 -->
@&#8203;switch (foo) {
  @&#8203;case (1) {}
  @&#8203;default never;
}
```

`arrow function` and `instanceof` expressions.

<!-- prettier-ignore -->

```html
<!-- Input -->
@&#8203;let fn = (a) =>        a?    1:2;

{{ fn ( a         instanceof b)}}

<!-- Prettier 3.8.1 -->
@&#8203;let fn = (a) =>        a?    1:2;

{{ fn ( a         instanceof b)}}

<!-- Prettier 3.8.2 -->
@&#8203;let fn = (a) => (a ? 1 : 2);

{{ fn(a instanceof b) }}
```

</details>

<details>
<summary>stylelint/stylelint (stylelint)</summary>

### [`v17.8.0`](https://github.com/stylelint/stylelint/blob/HEAD/CHANGELOG.md#1780---2026-04-15)

[Compare Source](https://github.com/stylelint/stylelint/compare/17.7.0...17.8.0)

It adds 3 new rules and 1 configuration property.

- Added: `languageOptions.directionality` configuration property ([#&#8203;8687](https://github.com/stylelint/stylelint/pull/8687)) ([@&#8203;sw1tch3roo](https://github.com/sw1tch3roo)).
- Added: `property-layout-mappings` rule ([#&#8203;8687](https://github.com/stylelint/stylelint/pull/8687)) ([@&#8203;sw1tch3roo](https://github.com/sw1tch3roo)).
- Added: `relative-selector-nesting-notation` rule ([#&#8203;8730](https://github.com/stylelint/stylelint/pull/8730)) ([@&#8203;sw1tch3roo](https://github.com/sw1tch3roo)).
- Added: `selector-no-deprecated` rule ([#&#8203;8694](https://github.com/stylelint/stylelint/pull/8694)) ([@&#8203;immitsu](https://github.com/immitsu)).

### [`v17.7.0`](https://github.com/stylelint/stylelint/blob/HEAD/CHANGELOG.md#1770---2026-04-12)

[Compare Source](https://github.com/stylelint/stylelint/compare/17.6.0...17.7.0)

It fixes 4 bugs, including clearer problem messages by removing filler words and leading with the problem. We've also released `1.0.0` of [create-stylelint](https://github.com/stylelint/create-stylelint) to help with first-time Stylelint setup.

- Fixed: clarity of problem messages ([#&#8203;9199](https://github.com/stylelint/stylelint/pull/9199)) ([@&#8203;jeddy3](https://github.com/jeddy3)).
- Fixed: `--print-config` CLI flag to hide internal properties ([#&#8203;9194](https://github.com/stylelint/stylelint/pull/9194)) ([@&#8203;ybiquitous](https://github.com/ybiquitous)).
- Fixed: `function-url-quotes` false positives when URLs have modifiers ([#&#8203;8702](https://github.com/stylelint/stylelint/pull/8702)) ([@&#8203;immitsu](https://github.com/immitsu)).
- Fixed: `selector-no-qualifying-type` false positives for `:has()` ([#&#8203;9182](https://github.com/stylelint/stylelint/pull/9182)) ([@&#8203;romainmenke](https://github.com/romainmenke)).

### [`v17.6.0`](https://github.com/stylelint/stylelint/blob/HEAD/CHANGELOG.md#1760---2026-03-26)

[Compare Source](https://github.com/stylelint/stylelint/compare/17.5.0...17.6.0)

It adds support for extending units in `languageOptions`, which then apply to rules like `declaration-property-value-no-unknown`, and fixes 2 bugs.

- Added: support for extending units to `languageOptions` ([#&#8203;9166](https://github.com/stylelint/stylelint/pull/9166)) ([@&#8203;jeddy3](https://github.com/jeddy3)).
- Fixed: missing `ruleMetadata` when linting multiple files with overrides ([#&#8203;9154](https://github.com/stylelint/stylelint/pull/9154)) ([@&#8203;kovsu](https://github.com/kovsu)).
- Fixed: `custom-property-no-missing-var-function` false positives for `timeline-scope` and `animation-timeline` ([#&#8203;9164](https://github.com/stylelint/stylelint/pull/9164)) ([@&#8203;splincode](https://github.com/splincode)).

### [`v17.5.0`](https://github.com/stylelint/stylelint/blob/HEAD/CHANGELOG.md#1750---2026-03-19)

[Compare Source](https://github.com/stylelint/stylelint/compare/17.4.0...17.5.0)

It deprecates two rule options, adds 1 rule option and fixes 7 bugs. We've also released [`2.1.0`](https://github.com/stylelint/vscode-stylelint/releases/tag/2.1.0) of [our VS Code extension](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint), which adds 8 new requested features, and our [first release](https://www.npmjs.com/package/@&#8203;stylelint/language-server) of the Stylelint Language Server.

- Deprecated: `*syntax` options from `declaration-property-value-no-unknown` ([#&#8203;9102](https://github.com/stylelint/stylelint/pull/9102)) ([@&#8203;ragini-pandey](https://github.com/ragini-pandey)).
- Added: `ignoreMediaFeatureNameValues: {}` to `media-feature-name-value-no-unknown` ([#&#8203;8976](https://github.com/stylelint/stylelint/pull/8976)) ([@&#8203;kovsu](https://github.com/kovsu)).
- Fixed: `node_modules` not ignored when using `codeFilename` in Node.js API ([#&#8203;9130](https://github.com/stylelint/stylelint/pull/9130)) ([@&#8203;adalinesimonian](https://github.com/adalinesimonian)).
- Fixed: `Error TS7016` for imported `css-tree` types ([#&#8203;9133](https://github.com/stylelint/stylelint/pull/9133)) ([@&#8203;ragini-pandey](https://github.com/ragini-pandey)).
- Fixed: `declaration-property-value-keyword-no-deprecated` false positives for function arguments ([#&#8203;9116](https://github.com/stylelint/stylelint/pull/9116)) ([@&#8203;ragini-pandey](https://github.com/ragini-pandey)).
- Fixed: `declaration-property-value-no-unknown` false positives for `calc-size()` containing `size` keyword ([#&#8203;9105](https://github.com/stylelint/stylelint/pull/9105)) ([@&#8203;hriztam](https://github.com/hriztam)).
- Fixed: `no-descending-specificity` & `no-duplicate-selectors` false negatives for equivalent compound selectors ([#&#8203;8977](https://github.com/stylelint/stylelint/pull/8977)) ([@&#8203;kovsu](https://github.com/kovsu)).
- Fixed: `no-invalid-position-declaration` false positives for `@mixin` and `@scope` ([#&#8203;9120](https://github.com/stylelint/stylelint/pull/9120)) ([@&#8203;ragini-pandey](https://github.com/ragini-pandey)).
- Fixed: `property-no-unknown` false negatives for `types` ([#&#8203;9117](https://github.com/stylelint/stylelint/pull/9117)) ([@&#8203;Mouvedia](https://github.com/Mouvedia)).

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://github.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS42MS4wIiwidXBkYXRlZEluVmVyIjoiNDEuNjEuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->

Reviewed-on: https://git.robbevp.be/robbevp/website-robbevanpetegem/pulls/508
Co-authored-by: Renovate Bot <renovate@robbevp.be>
Co-committed-by: Renovate Bot <renovate@robbevp.be>